"""Declarative base, shared column types and mixins."""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime
from typing import Any

from sqlalchemy import Date, DateTime, ForeignKey, MetaData, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def utcnow() -> datetime:
    return datetime.now(UTC)


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
    type_annotation_map = {
        uuid.UUID: UUID(as_uuid=True),
        datetime: DateTime(timezone=True),
        date: Date(),
        dict[str, Any]: JSONB(),
        list[str]: JSONB(),
    }


class IdMixin:
    """UUID primary key generated by the application.

    Generating ids client-side lets inserts skip `RETURNING`, which row-level security would
    otherwise check against SELECT policies before the caller's membership row exists.
    """

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(default=utcnow, onupdate=utcnow)


class TenantMixin:
    """Every tenant row names its family space; RLS policies key on this column."""

    @declared_attr
    def family_space_id(cls) -> Mapped[uuid.UUID]:  # noqa: N805 - declared_attr is per-class
        return mapped_column(
            ForeignKey("family_space.id", ondelete="CASCADE"), index=True, nullable=False
        )


class AuthoredMixin:
    created_by: Mapped[str] = mapped_column(String(255))
