"""Initial core schema: the M1 tables, keys, checks and indexes.

Revision ID: 0001
Revises:
Create Date: 2026-10-01

Row-level security follows in 0002.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_space",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("janua_organization_id", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_family_space")),
        sa.UniqueConstraint(
            "janua_organization_id", name=op.f("uq_family_space_janua_organization_id")
        ),
    )
    op.create_table(
        "waitlist_entry",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("aviso_version", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("relayed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_waitlist_entry")),
    )
    op.create_index(
        "uq_waitlist_entry_email_lower",
        "waitlist_entry",
        [sa.literal_column("lower(email)")],
        unique=True,
    )
    op.create_table(
        "assertion",
        sa.Column("subject_type", sa.String(length=20), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("asserted_by", sa.String(length=255), nullable=False),
        sa.Column("citation_ids", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("sensitivity", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "sensitivity IS NULL OR sensitivity IN ('religion', 'health', 'genetic', 'ethnicity', 'sexual', 'political')",
            name=op.f("ck_assertion_sensitivity"),
        ),
        sa.CheckConstraint(
            "status IN ('suggested', 'accepted', 'disputed', 'retracted')",
            name=op.f("ck_assertion_status"),
        ),
        sa.CheckConstraint(
            "subject_type IN ('person', 'event', 'relationship', 'place')",
            name=op.f("ck_assertion_subject_type"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_assertion_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["assertion.id"],
            name=op.f("fk_assertion_supersedes_id_assertion"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assertion")),
        sa.UniqueConstraint("supersedes_id", name=op.f("uq_assertion_supersedes_id")),
    )
    op.create_index(
        op.f("ix_assertion_family_space_id"), "assertion", ["family_space_id"], unique=False
    )
    op.create_index(
        "ix_assertion_subject",
        "assertion",
        ["family_space_id", "subject_type", "subject_id"],
        unique=False,
    )
    op.create_table(
        "person",
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("living_status", sa.String(length=10), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("sort_name", sa.Text(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "living_status IN ('living', 'deceased', 'unknown')",
            name=op.f("ck_person_living_status"),
        ),
        sa.CheckConstraint("sex IN ('M', 'F', 'X', 'U')", name=op.f("ck_person_sex")),
        sa.CheckConstraint(
            "visibility IN ('space', 'private', 'public_memorial')",
            name=op.f("ck_person_visibility"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_person_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person")),
        sa.UniqueConstraint("family_space_id", "id", name=op.f("uq_person_family_space_id_id")),
    )
    op.create_index(op.f("ix_person_family_space_id"), "person", ["family_space_id"], unique=False)
    op.create_index(
        "ix_person_space_sort", "person", ["family_space_id", "sort_name", "id"], unique=False
    )
    op.create_table(
        "place",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("inegi_code", sa.String(length=20), nullable=True),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "kind IN ('pais', 'estado', 'municipio', 'localidad', 'parroquia', 'hacienda', 'rancho', 'other')",
            name=op.f("ck_place_kind"),
        ),
        sa.CheckConstraint(
            "valid_from IS NULL OR valid_to IS NULL OR valid_from <= valid_to",
            name=op.f("ck_place_validity"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id", "parent_id"],
            ["place.family_space_id", "place.id"],
            name=op.f("fk_place_family_space_id_parent_id_place"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_place_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_place")),
        sa.UniqueConstraint("family_space_id", "id", name=op.f("uq_place_family_space_id_id")),
    )
    op.create_index(op.f("ix_place_family_space_id"), "place", ["family_space_id"], unique=False)
    op.create_table(
        "revision",
        sa.Column("actor_sub", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_revision_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revision")),
    )
    op.create_index(
        "ix_revision_entity",
        "revision",
        ["family_space_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_revision_family_space_id"), "revision", ["family_space_id"], unique=False
    )
    op.create_table(
        "source",
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("repository", sa.String(length=500), nullable=True),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "type IN ('parish_book', 'civil_registry_act', 'oral_interview', 'census', 'notarial_record', 'family_document', 'publication', 'website', 'other')",
            name=op.f("ck_source_type"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_source_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint("family_space_id", "id", name=op.f("uq_source_family_space_id_id")),
    )
    op.create_index(op.f("ix_source_family_space_id"), "source", ["family_space_id"], unique=False)
    op.create_index("ix_source_space_title", "source", ["family_space_id", "title"], unique=False)
    op.create_table(
        "space_member",
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.Column("user_sub", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('steward', 'editor', 'contributor', 'viewer')",
            name=op.f("ck_space_member_role"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_space_member_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_space_member")),
        sa.UniqueConstraint(
            "family_space_id", "user_sub", name=op.f("uq_space_member_family_space_id_user_sub")
        ),
    )
    op.create_index("ix_space_member_user_sub", "space_member", ["user_sub"], unique=False)
    op.create_table(
        "citation",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("page", sa.String(length=100), nullable=True),
        sa.Column("foja", sa.String(length=100), nullable=True),
        sa.Column("partida", sa.String(length=100), nullable=True),
        sa.Column("quality", sa.SmallInteger(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint("quality BETWEEN 0 AND 3", name=op.f("ck_citation_quality")),
        sa.ForeignKeyConstraint(
            ["family_space_id", "source_id"],
            ["source.family_space_id", "source.id"],
            name=op.f("fk_citation_family_space_id_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_citation_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_citation")),
    )
    op.create_index(
        op.f("ix_citation_family_space_id"), "citation", ["family_space_id"], unique=False
    )
    op.create_index(
        "ix_citation_source", "citation", ["family_space_id", "source_id"], unique=False
    )
    op.create_table(
        "event",
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("date_value", sa.String(length=100), nullable=True),
        sa.Column("date_earliest", sa.Date(), nullable=True),
        sa.Column("date_latest", sa.Date(), nullable=True),
        sa.Column("place_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sensitivity", sa.String(length=20), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "sensitivity IS NULL OR sensitivity IN ('religion', 'health', 'genetic', 'ethnicity', 'sexual', 'political')",
            name=op.f("ck_event_sensitivity"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id", "place_id"],
            ["place.family_space_id", "place.id"],
            name=op.f("fk_event_family_space_id_place_id_place"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_event_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
        sa.UniqueConstraint("family_space_id", "id", name=op.f("uq_event_family_space_id_id")),
    )
    op.create_index(op.f("ix_event_family_space_id"), "event", ["family_space_id"], unique=False)
    op.create_index("ix_event_space_type", "event", ["family_space_id", "type"], unique=False)
    op.create_table(
        "name_form",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("given", sa.String(length=200), nullable=True),
        sa.Column("apellido_paterno", sa.String(length=200), nullable=True),
        sa.Column("apellido_materno", sa.String(length=200), nullable=True),
        sa.Column("extra_surnames", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("particles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nombre_de_pila", sa.String(length=200), nullable=True),
        sa.Column("nombre_usado", sa.String(length=200), nullable=True),
        sa.Column("nicknames", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("name_type", sa.String(length=20), nullable=False),
        sa.Column("lang", sa.String(length=35), nullable=False),
        sa.Column("surname_order", sa.String(length=20), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "surname_order IN ('paterno_materno', 'materno_paterno', 'single')",
            name=op.f("ck_name_form_surname_order"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id", "person_id"],
            ["person.family_space_id", "person.id"],
            name=op.f("fk_name_form_family_space_id_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_name_form_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_name_form")),
    )
    op.create_index(
        op.f("ix_name_form_family_space_id"), "name_form", ["family_space_id"], unique=False
    )
    op.create_index("ix_name_form_person", "name_form", ["person_id", "position"], unique=False)
    op.create_table(
        "relationship",
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("from_person_id", sa.UUID(), nullable=False),
        sa.Column("to_person_id", sa.UUID(), nullable=False),
        sa.Column("qualifier", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint(
            "(type = 'parent_child' AND qualifier IN ('birth', 'adopted', 'foster', 'step', 'guardian', 'unknown') AND status IS NULL) OR (type = 'union' AND qualifier IN ('civil_marriage', 'religious_marriage', 'free_union', 'cohabitation') AND status IN ('active', 'divorced', 'separated', 'widowed', 'annulled'))",
            name=op.f("ck_relationship_qualifier"),
        ),
        sa.CheckConstraint("type IN ('parent_child', 'union')", name=op.f("ck_relationship_type")),
        sa.CheckConstraint("from_person_id <> to_person_id", name=op.f("ck_relationship_not_self")),
        sa.ForeignKeyConstraint(
            ["family_space_id", "from_person_id"],
            ["person.family_space_id", "person.id"],
            name=op.f("fk_relationship_family_space_id_from_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id", "to_person_id"],
            ["person.family_space_id", "person.id"],
            name=op.f("fk_relationship_family_space_id_to_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_relationship_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship")),
    )
    op.create_index(
        op.f("ix_relationship_family_space_id"), "relationship", ["family_space_id"], unique=False
    )
    op.create_index(
        "ix_relationship_from", "relationship", ["family_space_id", "from_person_id"], unique=False
    )
    op.create_index(
        "ix_relationship_to", "relationship", ["family_space_id", "to_person_id"], unique=False
    )
    op.create_table(
        "association",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("associate_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.CheckConstraint("role IN ('godparent', 'witness')", name=op.f("ck_association_role")),
        sa.CheckConstraint("person_id <> associate_id", name=op.f("ck_association_not_self")),
        sa.ForeignKeyConstraint(
            ["family_space_id", "associate_id"],
            ["person.family_space_id", "person.id"],
            name=op.f("fk_association_family_space_id_associate_id_person"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id", "event_id"],
            ["event.family_space_id", "event.id"],
            name=op.f("fk_association_family_space_id_event_id_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id", "person_id"],
            ["person.family_space_id", "person.id"],
            name=op.f("fk_association_family_space_id_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_association_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_association")),
        sa.UniqueConstraint(
            "event_id",
            "person_id",
            "associate_id",
            "role",
            name=op.f("uq_association_event_id_person_id_associate_id_role"),
        ),
    )
    op.create_index(
        op.f("ix_association_family_space_id"), "association", ["family_space_id"], unique=False
    )
    op.create_table(
        "event_participant",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("family_space_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "role IN ('principal', 'spouse', 'parent', 'godparent', 'witness', 'officiant', 'informant', 'other')",
            name=op.f("ck_event_participant_role"),
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id", "event_id"],
            ["event.family_space_id", "event.id"],
            name=op.f("fk_event_participant_family_space_id_event_id_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id", "person_id"],
            ["person.family_space_id", "person.id"],
            name=op.f("fk_event_participant_family_space_id_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["family_space_id"],
            ["family_space.id"],
            name=op.f("fk_event_participant_family_space_id_family_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_participant")),
        sa.UniqueConstraint(
            "event_id",
            "person_id",
            "role",
            name=op.f("uq_event_participant_event_id_person_id_role"),
        ),
    )
    op.create_index(
        op.f("ix_event_participant_family_space_id"),
        "event_participant",
        ["family_space_id"],
        unique=False,
    )
    op.create_index(
        "ix_event_participant_person",
        "event_participant",
        ["family_space_id", "person_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_participant_person", table_name="event_participant")
    op.drop_index(op.f("ix_event_participant_family_space_id"), table_name="event_participant")
    op.drop_table("event_participant")
    op.drop_index(op.f("ix_association_family_space_id"), table_name="association")
    op.drop_table("association")
    op.drop_index("ix_relationship_to", table_name="relationship")
    op.drop_index("ix_relationship_from", table_name="relationship")
    op.drop_index(op.f("ix_relationship_family_space_id"), table_name="relationship")
    op.drop_table("relationship")
    op.drop_index("ix_name_form_person", table_name="name_form")
    op.drop_index(op.f("ix_name_form_family_space_id"), table_name="name_form")
    op.drop_table("name_form")
    op.drop_index("ix_event_space_type", table_name="event")
    op.drop_index(op.f("ix_event_family_space_id"), table_name="event")
    op.drop_table("event")
    op.drop_index("ix_citation_source", table_name="citation")
    op.drop_index(op.f("ix_citation_family_space_id"), table_name="citation")
    op.drop_table("citation")
    op.drop_index("ix_space_member_user_sub", table_name="space_member")
    op.drop_table("space_member")
    op.drop_index("ix_source_space_title", table_name="source")
    op.drop_index(op.f("ix_source_family_space_id"), table_name="source")
    op.drop_table("source")
    op.drop_index(op.f("ix_revision_family_space_id"), table_name="revision")
    op.drop_index("ix_revision_entity", table_name="revision")
    op.drop_table("revision")
    op.drop_index(op.f("ix_place_family_space_id"), table_name="place")
    op.drop_table("place")
    op.drop_index("ix_person_space_sort", table_name="person")
    op.drop_index(op.f("ix_person_family_space_id"), table_name="person")
    op.drop_table("person")
    op.drop_index("ix_assertion_subject", table_name="assertion")
    op.drop_index(op.f("ix_assertion_family_space_id"), table_name="assertion")
    op.drop_table("assertion")
    op.drop_index("uq_waitlist_entry_email_lower", table_name="waitlist_entry")
    op.drop_table("waitlist_entry")
    op.drop_table("family_space")
    # ### end Alembic commands ###
